import type { CarroFormData } from '@/types/carro';

/**
 * Blank car-wizard form. Shared by the Anunciar wizard and the Standvirtual
 * import prefill so both start from the same baseline (contact fields are
 * layered on top from the profile by each caller).
 */
export const EMPTY_CARRO_FORM_DATA: CarroFormData = {
  marca: '',
  modelo: '',
  anoFabricacao: '',
  anoModelo: '',
  km: '',
  cor: '',
  combustivel: 'Gasolina',
  cambio: 'Manual',
  portas: '',
  bodyType: '',
  seats: '',
  condition: 'Usado',
  power: '',
  displacement: '',
  traction: '',
  features: [],
  version: '',
  firstRegistrationMonth: '',
  origin: '',
  previousOwners: '',
  gears: '',
  co2Emissions: '',
  maxFuelRange: '',
  consumptionUrban: '',
  consumptionExtraUrban: '',
  consumptionCombined: '',
  upholstery: '',
  numberOfAirbags: '',
  warrantyMonths: '',
  acceptsFinancing: false,
  vatDeductible: false,
  acceptsExchange: false,
  localizacao: '',
  localizacaoDistrito: '',
  bairro: '',
  preco: '',
  descricao: '',
  descricaoGeradaIA: false,
  videoUrl: '',
  estadoVeiculo: 'pronto',
  rodando: 'sim',
  inspecao: 'sim',
  tiposManutencao: [],
  orcamentoTexto: '',
  incluirMecanicoNome: false,
  incluirMecanicoTelefone: false,
  mecanicoNome: '',
  mecanicoTelefone: '',
  vendedorWhatsApp: '',
  vendedorTelefone: '',
  vendedorEmail: '',
};
