import type { ExpoConfig, ConfigContext } from 'expo/config';
import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

// Reference a native Firebase file only when it exists, so building for a single
// platform (e.g. Android only) doesn't warn about the other platform's missing
// credentials file.
const firebaseFile = (name: string): string | undefined => {
  const p = join(__dirname, 'firebase', name);
  return existsSync(p) ? `./firebase/${name}` : undefined;
};

/**
 * RecarGarage mobile app config.
 *
 * Native Firebase credentials are NOT committed. They live in `./firebase/`
 * and are wired into each build through `googleServicesFile` below:
 *   - iOS:     firebase/GoogleService-Info.plist
 *   - Android: firebase/google-services.json
 *
 * See `firebase/README.md` for how to obtain and place these files.
 *
 * The bundle identifier / package name is `com.recargarage` on both platforms.
 */

const BUNDLE_ID = 'com.recargarage';

// Reversed iOS OAuth client id used by Google Sign-In's iosUrlScheme. Prefer an
// explicit `GOOGLE_IOS_URL_SCHEME` env var; otherwise derive it from the
// REVERSED_CLIENT_ID key in the committed GoogleService-Info.plist. Shipping a
// placeholder here makes App Store Connect reject the upload (error 90158), so
// the build fails loudly instead of falling back to a dummy scheme.
const reversedClientIdFromPlist = (): string | undefined => {
  const p = join(__dirname, 'firebase', 'GoogleService-Info.plist');
  if (!existsSync(p)) return undefined;
  const m = readFileSync(p, 'utf8').match(
    /<key>REVERSED_CLIENT_ID<\/key>\s*<string>([^<]+)<\/string>/,
  );
  return m?.[1];
};
const GOOGLE_IOS_URL_SCHEME =
  process.env.GOOGLE_IOS_URL_SCHEME ?? reversedClientIdFromPlist();
if (!GOOGLE_IOS_URL_SCHEME) {
  throw new Error(
    'Google Sign-In iosUrlScheme is unset: set GOOGLE_IOS_URL_SCHEME or add ' +
      'REVERSED_CLIENT_ID to firebase/GoogleService-Info.plist.',
  );
}

// EAS project id — set after `eas init` (e.g. in `.env` or EAS env). It powers
// both `extra.eas.projectId` and the EAS Update endpoint below.
const EAS_PROJECT_ID = process.env.EAS_PROJECT_ID ?? undefined;

// iOS APNs environment baked into the `aps-environment` entitlement. TestFlight
// and App Store builds run against PRODUCTION APNs, so they must ship the
// `production` entitlement — otherwise the device registers a sandbox token and
// FCM delivery is silently dropped (BadDeviceToken). `expo-notifications`
// defaults this to `development`, which only suits dev-client/sandbox builds.
// The `preview`/`production` EAS profiles set APS_ENVIRONMENT=production; local
// dev builds fall back to `development`.
const APS_ENVIRONMENT =
  process.env.APS_ENVIRONMENT === 'production' ? 'production' : 'development';
const VERSION = '1.6.0';
const BUILD_NUMBER = 60;

export default ({ config }: ConfigContext): ExpoConfig => ({
  ...config,
  name: 'RecarGarage',
  slug: 'recargarage',
  scheme: 'recargarage',
  version: VERSION,
  orientation: 'portrait',
  icon: './assets/icon.png',
  userInterfaceStyle: 'light',
  backgroundColor: '#ffffff',
  // --- OTA updates (EAS Update / expo-updates) ---
  // `fingerprint` ties each JS bundle to the exact native runtime that produced
  // it. Because we use Continuous Native Generation (ios/ and android/ are
  // gitignored, regenerated by `expo prebuild`), the fingerprint changes
  // automatically whenever native deps/config change — so an OTA update can
  // NEVER be delivered to an incompatible binary. Bundle id stays `com.recargarage`.
  runtimeVersion: { policy: 'fingerprint' },
  // The `updates` block only takes effect once EAS_PROJECT_ID is set (after
  // `eas init`). We drive checks ourselves from `useOTAUpdates()`, so we disable
  // the automatic load-time check and never block launch on the network.
  updates: EAS_PROJECT_ID
    ? {
        url: "https://u.expo.dev/2b361ebe-abb0-4514-b884-a0db195e07a5",
        fallbackToCacheTimeout: 0,
        checkAutomatically: 'ON_ERROR_RECOVERY',
      }
    : undefined,
  splash: {
    image: './assets/splash-icon.png',
    resizeMode: 'contain',
    backgroundColor: '#ffffff',
  },
  assetBundlePatterns: ['**/*'],
  ios: {
    buildNumber: BUILD_NUMBER.toString(),
    bundleIdentifier: BUNDLE_ID,
    supportsTablet: true,
    googleServicesFile: firebaseFile('GoogleService-Info.plist'),
    // Required for Sign in with Apple (App Store Guideline 4.8).
    usesAppleSignIn: true,
    infoPlist: {
      ITSAppUsesNonExemptEncryption: false,
    },
  },
  android: {
    package: BUNDLE_ID,
    versionCode: BUILD_NUMBER,
    googleServicesFile: firebaseFile('google-services.json'),
    adaptiveIcon: {
      foregroundImage: './assets/adaptive-icon.png',
      backgroundColor: '#ffffff',
    },
    // Android maps use Google Maps and need an API key. iOS uses Apple Maps
    // (no key). Set EXPO_PUBLIC_GOOGLE_MAPS_API_KEY in .env / EAS.
    config: {
      googleMaps: { apiKey: process.env.EXPO_PUBLIC_GOOGLE_MAPS_API_KEY ?? '' },
    },
    // No location/media permissions. Notifications (POST_NOTIFICATIONS on
    // Android 13+) are contributed by expo-notifications below. Location
    // (Fase 5) arrives with its feature.
    permissions: [],
  },
  web: {
    bundler: 'metro',
    output: 'static',
    favicon: './assets/favicon.png',
  },
  plugins: [
    // Installs the shared debug keystore so every machine/CI signs with the
    // same SHA-1 (stable Google Sign-In). See plugins/withDebugKeystore.js.
    './plugins/withDebugKeystore',
    // Release signing from .env creds (RG_UPLOAD_*) — see android:bundle script.
    './plugins/withAndroidReleaseSigning',
    // Listed first so its withAndroidManifest mod runs LAST (manifest mods
    // execute in reverse plugin order) — by then expo-notifications has added
    // the default_notification_color meta-data we need to mark tools:replace.
    './plugins/withFirebaseNotificationFix',
    'expo-router',
    'expo-secure-store',
    'expo-apple-authentication',
    '@react-native-firebase/app',
    '@react-native-firebase/auth',
    '@react-native-firebase/messaging',
    [
      'expo-notifications',
      {
        icon: './assets/notification-icon.png',
        color: '#0b4f9e',
        // Match the APNs environment to the build (see APS_ENVIRONMENT above).
        // Without `production`, TestFlight/App Store pushes never arrive.
        mode: APS_ENVIRONMENT,
        // Add `UIBackgroundModes: [remote-notification]` so pushes are handled
        // with the app backgrounded/quit — not added by the plugin otherwise.
        enableBackgroundRemoteNotifications: true,
      },
    ],
    [
      'expo-build-properties',
      {
        // React Native Firebase requires static frameworks on iOS.
        // `buildReactNativeFromSource` works around the firestore (v24+) Swift
        // build failure under Xcode 26 / RN 0.83: the new RNFBFirestore Swift
        // sources force Clang to build the RNFBFirestore ObjC module, which
        // imports React types (RCTBridgeModule, RCTPromiseRejectBlock). The
        // prebuilt RNCore binary's module map doesn't expose those for a
        // modular import, so we build React Native from source instead.
        // See invertase/react-native-firebase#8657, expo/expo#39233.
        ios: { useFrameworks: 'static', buildReactNativeFromSource: true },
        android: {},
      },
    ],
    [
      '@react-native-google-signin/google-signin',
      { iosUrlScheme: GOOGLE_IOS_URL_SCHEME },
    ],
    [
      'expo-image-picker',
      {
        // Gallery uses the system Photo Picker → no photo-library permission
        // (avoids the Google Play "Photo & Video Permissions" declaration).
        // We never record audio, so block the microphone permission too.
        photosPermission: false,
        microphonePermission: false,
        cameraPermission:
          'A RecarGarage usa a câmara apenas quando tira uma foto para o seu anúncio.',
      },
    ],
    [
      'expo-location',
      {
        locationWhenInUsePermission:
          'A RecarGarage usa a sua localização apenas para mostrar oficinas perto de si no mapa.',
      },
    ],
    [
      'expo-splash-screen',
      {
        image: './assets/splash-icon.png',
        imageWidth: 180,
        resizeMode: 'contain',
        backgroundColor: '#ffffff',
      },
    ],
  ],
  experiments: {
    typedRoutes: true,
  },
  extra: {
    router: {},
    eas: {
      // Fill in after `eas init` (set EAS_PROJECT_ID in `.env` / EAS env).
      projectId: "2b361ebe-abb0-4514-b884-a0db195e07a5",
    },
  },
});
