import type { Timestamp } from 'firebase/firestore';
import type { DamageDetectionResult } from './ia';
import type { Country } from '@/lib/country';
import type { PhotoAngles } from '@/lib/spin360';

export type EstadoVeiculo = 'pronto' | 'manutencao';
export type Combustivel = 'Gasolina' | 'Etanol' | 'Flex' | 'Diesel' | 'Elétrico' | 'Híbrido';
export type Cambio = 'Manual' | 'Automático' | 'CVT';
export type BodyType =
  | 'Citadino'
  | 'Utilitário'
  | 'Sedan'
  | 'Carrinha'
  | 'SUV'
  | 'Monovolume'
  | 'Coupé'
  | 'Cabrio'
  | 'Pick-up';
export type Condition = 'Novo' | 'Usado' | 'Para peças';
export type Traction = 'Dianteira' | 'Traseira' | 'Integral (4x4)';
export type VehicleOrigin = 'Nacional' | 'Importado';
export type Upholstery = 'Tecido' | 'Couro' | 'Couro sintético' | 'Alcântara' | 'Outro';
export type FiltroAtivo = 'lowcost' | '500' | '1000' | 'reparar' | 'qualquer' | null;
export type SortOrdem = 'crescente' | 'decrescente' | null;
export type FiltroChip = { label: string; value: string };
export type StatusAnuncio = 'pendente' | 'aprovado' | 'rejeitado';
export type OrigemAnuncio = 'manual' | 'standvirtual';

export interface Carro {
  id: string;
  marca: string;
  modelo: string;
  anoFabricacao: number;
  anoModelo?: number;
  preco: number;
  km: number;
  combustivel: Combustivel;
  cambio: Cambio;
  cor: string;
  portas: number;
  bodyType?: BodyType;
  seats?: number;
  condition?: Condition;
  power?: number;
  displacement?: number;
  traction?: Traction;
  features?: string[];
  /** Trim / variant, e.g. "CDi Avantgarde" (Standvirtual "version"). */
  version?: string;
  /** Month of first registration (1–12), pairs with anoFabricacao as the year. */
  firstRegistrationMonth?: number;
  origin?: VehicleOrigin;
  /** Number of previous owners (0 = seller is the first owner). */
  previousOwners?: number;
  /** Number of forward gears. */
  gears?: number;
  /** Combined CO₂ emissions, g/km. */
  co2Emissions?: number;
  /** Max fuel/electric range, km. */
  maxFuelRange?: number;
  /** Fuel consumption, l/100 km. */
  consumptionUrban?: number;
  consumptionExtraUrban?: number;
  consumptionCombined?: number;
  upholstery?: Upholstery;
  numberOfAirbags?: number;
  /** Remaining vendor warranty, in months. */
  warrantyMonths?: number;
  acceptsFinancing?: boolean;
  /** VAT-deductible invoice available (IVA dedutível). */
  vatDeductible?: boolean;
  /** Seller accepts a trade-in / part-exchange (retoma). */
  acceptsExchange?: boolean;
  local: string;
  distrito?: string;
  /** Neighbourhood — Brazilian listings only ("bairro"); unused for PT. */
  bairro?: string;
  coordenadas?: { lat: number; lng: number };
  /** Market the listing belongs to. Docs created before the Brazil launch have none — resolve with docCountry() (missing = PT). */
  country?: Country;
  descricao: string;
  videoUrl?: string;
  estadoVeiculo: EstadoVeiculo;
  tiposManutencao: string[];
  manutencaoOutro?: string;
  temOrcamento?: boolean;
  orcamentoTexto?: string;
  incluirMecanicoNome?: boolean;
  mecanicoNome?: string;
  incluirMecanicoTelefone?: boolean;
  mecanicoTelefone?: string;
  fotos: string[];
  /** Vehicle angle → index into `fotos`; enables the 360 spin viewer (see src/lib/spin360.ts). */
  photoAngles?: PhotoAngles | null;
  criador: string;
  criadorUid?: string;
  vendedorNome?: string;
  vendedorTelefone?: string;
  vendedorWhatsApp?: string;
  vendedorEmail?: string;
  rodando?: boolean;
  inspecao?: boolean;
  status: StatusAnuncio;
  dataCriacao: Timestamp;
  dataAprovacao?: Timestamp;
  impulso?: {
    ativo: boolean;
    dataInicio?: Timestamp;
    dataFim?: Timestamp;
  };
  visualizacoes?: number;
  contagemMensagens?: number;
  contagemFavoritos?: number;
  /** True when the description was generated by the AI assistant (plan 4.1). */
  descricaoGeradaIA?: boolean;
  /** Per-photo damage analysis cache, keyed by photo-URL hash. Written server-side only. */
  damageAnalysis?: Record<string, DamageDetectionResult>;
  /** Where the listing came from (plan 24). Absent means created manually. */
  origem?: OrigemAnuncio;
  /** Source advert id (the URL ID token) — duplicate-import detection key. */
  origemId?: string;
  /** Canonical source advert URL (audit trail). */
  origemUrl?: string;
  importadoEm?: Timestamp;
  /** Uid of who ran the import when it wasn't the owner (admin-on-behalf). */
  importadoPor?: string;
}

export type CarroInput = Omit<Carro, 'id' | 'dataCriacao'> & { dataCriacao?: Timestamp };

export interface CarroFormData {
  marca: string;
  modelo: string;
  anoFabricacao: string;
  anoModelo: string;
  km: string;
  cor: string;
  combustivel: Combustivel;
  cambio: Cambio;
  portas: string;
  bodyType: string;
  seats: string;
  condition: string;
  power: string;
  displacement: string;
  traction: string;
  features: string[];
  version: string;
  firstRegistrationMonth: string;
  origin: string;
  previousOwners: string;
  gears: string;
  co2Emissions: string;
  maxFuelRange: string;
  consumptionUrban: string;
  consumptionExtraUrban: string;
  consumptionCombined: string;
  upholstery: string;
  numberOfAirbags: string;
  warrantyMonths: string;
  acceptsFinancing: boolean;
  vatDeductible: boolean;
  acceptsExchange: boolean;
  localizacao: string;
  localizacaoDistrito: string;
  /** BR only — optional neighbourhood typed by the seller. */
  bairro: string;
  preco: string;
  descricao: string;
  descricaoGeradaIA: boolean;
  videoUrl: string;
  estadoVeiculo: EstadoVeiculo;
  rodando: string;
  inspecao: string;
  tiposManutencao: string[];
  orcamentoTexto: string;
  incluirMecanicoNome: boolean;
  incluirMecanicoTelefone: boolean;
  mecanicoNome: string;
  mecanicoTelefone: string;
  vendedorWhatsApp: string;
  vendedorTelefone: string;
  vendedorEmail: string;
}
