import type { Timestamp } from 'firebase/firestore';

export type TipoLead = 'financiamento' | 'seguro';
export type CoberturaSeguro = 'civil' | 'danos';

/**
 * Qualified lead generated by the financing / insurance simulator and shared
 * with partner institutions. Stored only after explicit user consent (RGPD).
 */
export interface LeadParceria {
  id: string;
  tipo: TipoLead;
  nome: string;
  email: string;
  telefone: string;
  consentimento: boolean;
  origem: string;
  // Listing context (optional)
  carroId?: string;
  carroTitulo?: string;
  carroPreco?: number;
  // Financing fields
  entrada?: number;
  meses?: number;
  prestacaoEstimada?: number;
  // Insurance fields
  idadeCondutor?: number;
  cobertura?: CoberturaSeguro;
  premioEstimado?: number;
  criadaEm: Timestamp;
}

export type LeadParceriaInput = Omit<LeadParceria, 'id' | 'criadaEm'>;
